### ISSUE TITLE
Button to clear content of Evaluate Toolbar

### ISSUE THREAD

**Issue by grumpygeek** [JustOff/error-console2-pm#1]
Be nice to have a button to clear content entered in the text input box of "Evalutate Toolbar".   

This would be especially useful since clicking in the text does not select all text as it does in browsers URL bar for example. I understand that not selecting all on click is useful for small editing changes so not expecting that to be changed.

**Comment by JustOff** [comment]
Did you try the triple-click?

**Comment by grumpygeek** [comment]
No, and I won't use it (other, familiar methods are easier to remember).   But nevermind.
